[profile.default]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "foundry-rs/forge-std=lib/forge-std/src/",
    "@balancer/balancer-v2-monorepo/pkg/=lib/balancer-v2-monorepo/pkg/",
    "@openzeppelin/openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
    "@aave/v3-core/contracts=lib/aave-v3-core/contracts",
    "@compound/contracts=lib/comet/contracts",
]

fuzz_runs = 1000

[profile.ci]
verbosity = 4

gas_reports = ["optimal"]


[etherscan]
84532 = { key = "${API_KEY}", url = "https://api-sepolia.basescan.org/api" }
